In [1]:
import numpy as np

# Q1

In [41]:
a = np.array([1,3,2,5,4])
print(np.median(a))

3.0


# Q2

In [45]:
a = np.array([3, 1, 7, 2, 9, 4])
print("a.min=",a.min())
print("a.max=",a.max())

a.min= 1
a.max= 9


# Q3

In [47]:
a = np.array([2,4,4,4,5,5,7,9])
print(np.var(a))
print(np.std(a)**2)
# same value

4.0
4.0


# Q4

In [52]:
a = np.array([3, 1, 7, 2, 9, 4])
print(a.argmin())
print(a.argmax())

1
4


# Q5

In [53]:
a = np.arange(1, 6)
# 1,2,3,4,5
print(a.mean())

3.0


# Q6

In [54]:
a = np.array([2,4,4,4,5,5,7,9])
print(np.std(a))

2.0


# Q7

In [55]:
a = np.array([1,5,3,8,2]) 
print(a > 3)

[False  True False  True False]


# Q8

In [56]:
a = np.array([1,2,3])
b = np.array([1,5,3])
print(a == b)

[ True False  True]


# Q9

In [57]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(np.array_equal(a,b))

True


# Q10

In [59]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((m1, m2), axis=0))
print(np.concatenate((m1, m2), axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Q11

In [60]:
a = np.array([[1,2],[3,4]])
print(a.sum(axis=0))

[4 6]


# Q12

In [61]:
a = np.array([1, 2, 3, 4])
print(a.cumsum())

[ 1  3  6 10]


# Q13

In [62]:
a = np.array([2,4,4,4,5,5,7,9])
print(np.std(a))

2.0


# Q14

In [63]:
x = np.array([1,2,3])
y = np.array([2,4,6])
np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

# Q15 (extra because of refresh page)

In [64]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))
print(np.concatenate((a, b, a)))


[1 2 3 4]
[1 2 3 4 1 2]


# learning and exercises

In [10]:
a = np.array([1, 2, 3])
b = np.array([1, 5, 3])
print(a == b)
print(a != b)

print(a[a == b])

[ True False  True]
[False  True False]
[1 3]


In [13]:
a = np.array([1, 2, 3])
print(a < 2)
print(a >= 2)

vals = np.array([5, 12, 3, 8, 1])
print(vals[vals > 5])

[ True False False]
[False  True  True]
[12  8]


In [21]:
print(np.array_equal(np.array([1, 2]), np.array([1,2])))
print(np.array_equal(np.array([1,2]), np.array([1,9])))
print(np.array_equal(np.array([1,2]), np.array([[1,2]])))
np.allclose(np.array([0.1+0.2]), np.array([0.3]))

True
False
False


True

In [26]:
a = np.array([1, 2, 3, 4])
print(a.sum())

b = np.array([[1,2,3],[4,5,6]])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.sum())


10
[5 7 9]
[ 6 15]
21


In [29]:
b = np.array([[1,2,3],
              [4,2,6]])
print(b.min())
print(b.max(axis=0))
print(b.min(axis=1))
print(b.argmax())

1
[4 2 6]
[1 2]
5


In [30]:
a = np.array([4,1,9,2,7])
print(a.argmin())
print(a.argmax())

b = np.array([[1,5,3],
              [4,2,6]])
print(b.argmax(axis=0))
print(b.argmax(axis=1))

1
2
[1 0 1]
[1 2]


In [31]:
a = np.arange(0,10)
print(a.mean())

b = np.array([[1,2,3],
              [4,5,6]])
print(b.mean(axis=0))
print(b.mean(axis=1))

4.5
[2.5 3.5 4.5]
[2. 5.]


In [32]:
a = np.array([1,3,2,5,4])
print(np.median(a))

b = np.array([1,3,2,5,4,1000])
print(np.median(b))
print(b.mean())

3.0
3.5
169.16666666666666


In [35]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.corrcoef(x,y))

r = np.corrcoef(x,y)[0,1]
print(r)

[[1. 1.]
 [1. 1.]]
1.0


In [38]:
a = np.array([2,4,4,4,5,5,7,9])
print(np.std(a))
print(np.std(a, ddof=1))
print(a.mean())

2.0
2.138089935299395
5.0


In [39]:
a = np.array([2,4,4,4,5,5,7,9])
print(np.var(a))
print(np.std(a)**2)
print(np.var(a, ddof=1))

4.0
4.0
4.571428571428571


In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print(np.concatenate((m1,m2),axis=0))

print(np.concatenate((m1,m2),axis=1))

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
